import type { Metadata } from 'next';
import { Gaegu as FontSans } from 'next/font/google';
import { cn } from '@/lib/utils';
import { ThemeProvider } from '@/providers/ThemeProvider';
import '@/styles/globals.css';
import { Toaster } from '@/components/ui/toaster';
import { SessionProvider } from '@/providers/SessionProvider';

export const fontSans = FontSans({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-sans',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          'min-h-screen bg-background-base font-sans antialiased',
          fontSans.variable
        )}
        suppressHydrationWarning={true}
      >
        <SessionProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <>
              {children}
              <Toaster />
            </>
          </ThemeProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
